import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'Vision',
      label: '1. Vision Document',
    },
    {
      type: 'doc',
      id: 'SRS',
      label: '2. Software Requirements Specification',
    },
    {
      type: 'category',
      label: '3. Architecture',
      link: {
        type: 'generated-index',
        title: 'Architecture Overview',
        description: 'Detailed description of the architectural decisions and system components.',
        slug: '/architecture',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Diagrams',
          link: { type: 'generated-index', title: 'Diagrams Overview', slug: '/architecture/diagrams' },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: '03_Architecture/Diagrams'
            }
          ],
        },
        {
          type: 'category',
          label: 'ADRs (Architecture Decision Records)',
          link: { type: 'generated-index', title: 'ADRs Overview', slug: '/architecture/adrs' },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: '03_Architecture/ADRs'
            }
          ],
        },
      ],
    },
  ],
};

export default sidebars;