import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'Vision',
      label: '1. Vision Document',
    },
    {
      type: 'doc',
      id: 'SRS',
      label: '2. Software Requirements Specification',
    },
    {
      type: 'category',
      label: '3. Architecture',
      link: {
        type: 'generated-index',
        title: 'Architecture Overview',
        description: 'Detailed description of the architectural decisions and system components.',
        slug: '/architecture',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Diagrams',
          link: { type: 'generated-index', title: 'Diagrams Overview', slug: '/architecture/diagrams' },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: '03_Architecture/Diagrams'
            }
          ],
        },
        {
          type: 'category',
          label: 'ADRs (Architecture Decision Records)',
          link: { type: 'generated-index', title: 'ADRs Overview', slug: '/architecture/adrs' },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: '03_Architecture/ADRs'
            }
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '4. DevOps',
      link: { type: 'generated-index', title: 'DevOps Overview', slug: '/devops' },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '04_DevOps'
        }
      ],
    },
    {
      type: 'category',
      label: '5. API',
      link: { type: 'generated-index', title: 'API Overview', slug: '/api' },
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'API/API_Contracts',
          label: 'API Contracts'
        },
        {
          type: 'category',
          label: 'Proto Definitions',
          link: { type: 'generated-index', title: 'Proto Definitions', slug: '/api/proto-definitions' },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: '05_API/02_Proto_Definitions'
            }
          ],
        },
        {
          type: 'doc',
          id: 'API/Error_Handling',
          label: 'API Error Handling'
        },
      ],
    },
    {
      type: 'category',
      label: '6. Data',
      link: { type: 'generated-index', title: 'Data Overview', slug: '/data' },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '06_Data'
        }
      ],
    },
    {
      type: 'category',
      label: '7. Security',
      link: { type: 'generated-index', title: 'Security Overview', slug: '/security' },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '07_Security'
        }
      ],
    },
    {
      type: 'category',
      label: '8. Testing',
      link: { type: 'generated-index', title: 'Testing Overview', slug: '/testing' },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '08_Testing'
        }
      ],
    },
  ],
};

export default sidebars;