name: CD Deploy Docusaurus Docs

on:
  workflow_run:
    workflows: ["CI Build Docusaurus Docs"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download Docusaurus build artifact
        uses: actions/download-artifact@v4
        with:
          name: docusaurus-build-artifact
          path: ./build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact and Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
        with:
          artifact_path: ./build